language: node_js
node_js:
- '0.10'
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# after_script:
#   - cat coverage/*/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
# addons:
#   code_climate:
#     repo_token: 96d3b0db17f941211ea2b3e568a5b2fe3868a54e819073fa8acc59c3d72727a7