language: node_js
node_js:
- '8'
cache: yarn
before_install:
- export DISPLAY=:99.0
- if [ -f /etc/init.d/xvfb ];then sh -e /etc/init.d/xvfb start; fi
before_script:
- npm start > /dev/null &
- if [ -n "$SAUCELABS" ]; then sleep 10;./node_modules/opentok-test-scripts/plugin-installer/packageSauceLabsInstaller.sh;mv ./node_modules/opentok-test-scripts/plugin-installer/SauceLabsInstaller.exe public/; fi
after_success:
- cat coverage/*/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
addons:
  code_climate:
    repo_token: 664b3bd95bef5ad8f8126fad7db731a0c9aaedbbc42223a1c3f668c550ab22a9
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libpango1.0-dev
services:
- redis-server
sudo: required
dist: trusty
matrix:
  fast_finish: true

  include:
    - os: linux
      env: UNIT_CMD='npm run lint' INTEGRATION_CMD=''
    - os: linux
      env: BROWSER=chrome  BVER=64.0.3282.140
    - os: linux
      env: BROWSER=firefox BVER=45.0.2
    - os: linux
      env: BROWSER=ie BVER=11 SAUCELABS=true
    - os: linux
      env: BROWSER=firefox BVER=stable INTEGRATION_CMD=''
    - os: linux
      env: BROWSER=firefox BVER=beta INTEGRATION_CMD=''
    - os: linux
      env: BROWSER=chrome  BVER=beta
    - os: osx
      osx_image: xcode9.2
      sudo: required
      env: BROWSER=safari BVER=unstable INTEGRATION_CMD=''

  allow_failures:
    - os: linux
      env: BROWSER=firefox BVER=45.0.2
    - os: linux
      env: BROWSER=chrome  BVER=beta
    - os: linux
      env: BROWSER=firefox BVER=beta INTEGRATION_CMD=''
    - os: osx
      osx_image: xcode9.2
      sudo: required
      env: BROWSER=safari BVER=unstable INTEGRATION_CMD=''

env:
  global:
  - TRAVIS=true
  - PORT=5000
  - CHROME_EXTENSION_ID=none
  - OT_API_KEY=1974561
  - BROWSERSTACK_USERNAME=adamullman1
  - UNIT_CMD='npm run unit'
  - INTEGRATION_CMD='npm run integration'
  - secure: ATYQg+EY0uo9KRx3su5NwijIMDIpPu8axX9AeATzjz3ree73eDU/jM0pTxV0tTLRtmMoC8b95DIvrhDfKIUXqTA4m2eHiwamv4+7Ocr7twEQJ6tjA3jX2Zv7H6QFZEGC1hIl7CJm4q9vMiS1NfVgG4VHTSsYkWCldwKyQvpfm9g=
  - secure: gXLtG+aBTQCJ4ovSwexMF38V5f56jBgxhyJaUC/lAzdQuyK5VFWCTubohOohFx4GokfN5A4JETVRiFfn4heRVmBxi5ZAlWwZpbWD6yBBu4l5SN7ST1umwzGEc+1zjZ0LyvaC8LK7GI7gdCVY+XWP1SryS1n9JEytiR1S93giflQ=
  - secure: UTGPkvGdlise2HWGIDGQvQAItv4zw2PZFOeIHOSvKBn2vuzhN8pX8OVR44n3Ddr28aW7YQkCLWKEsHsBgdsxUmWoFBnUrVX12dPKAjTq3gMeHuPAxkg6nBQJ4/y9r57wenAjGCd79H9n04jQtvDZkfe1+hpTLCMnMPkceIZdxO0=
  - secure: H8AA0IvOE8HpZgsQdHXUq110NtvheQEy76ZNGZU7mF4bNAfQ0PVWVpJ+HL/1itJFBVlGiu+MqzKJ2MtdhrlrBxYBcyM1yHdfCkoM6Uh2ff4hEGbZsZ65ClzgvnhabUQrzFGn3Qidba9ICKspdl0jXrhRnpbnN22kPGM9w/Izvv0=
